version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      non-major-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
